name: Deploymen
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Deploy to GCP VM
       uses: wshihadeh/docker-deployment-action@v1
       with:
         remote_docker_host: search-api@35.206.254.189
         ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
         ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
         deploy_path: /
